### ISSUE TITLE
Cannot fine the dataset "CMP-8objs"

### ISSUE THREAD

**Issue by GuoChris** [arxeiss/fast-3d-object-detection#1]
Hello, I am very interested in your code. But I have a problem.
In the file loading.cpp,
`int loadAllTemplates(FolderTemplateList &templates) {
	std::string folders[] = {
		"images/CMP-8objs/train-opt2/0-block/",
		"images/CMP-8objs/train-opt2/1-bridge/",
		"images/CMP-8objs/train-opt2/2-cup/",
		"images/CMP-8objs/train-opt2/3-driver/",
		"images/CMP-8objs/train-opt2/4-eye/",
		"images/CMP-8objs/train-opt2/5-lid/",
		"images/CMP-8objs/train-opt2/6-screw/",
		"images/CMP-8objs/train-opt2/7-whiteblock/"
	};`
But I cannot fine the dataset "CMP-8objs". Would you like to share this dataset or tell me how to find it?

**Comment by arxeiss** [comment]
Hello,

thank you for the message. This is my master thesis and I used this repo as "backup" basically. I will try to update README during weekend and also upload dataset. But the dataset itself constist of more than 12 000 templates, so I will probably upload it somewhere else and put here a link.

**Comment by GuoChris** [comment]
Thank you very much.
Waiting for your upload.
Best wishes to you

**Comment by arxeiss** [comment]
Hello,

sorry for the delay. You can download them here https://dspace.vsb.cz/handle/10084/128655 the link "Příloha" and I did a mirror into my [Google Drive](https://drive.google.com/file/d/1vC1LLoWhOYyRmsxxZ_zYVuLIQdid1Qwi/view?usp=sharing) as well.

Hope it helps

**Comment by arxeiss** [comment]
Please, check the code again. I found I did not upload everything. There is some cleaning done in the code.

**Comment by GuoChris** [comment]
Thank you very much!


Best wishes to you!



じ☆ve楓葉


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Pavel Kutáč"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月12日(星期三) 凌晨1:33
收件人:&nbsp;"arxeiss/fast-3d-object-detection"<fast-3d-object-detection@noreply.github.com&gt;;
抄送:&nbsp;"郭永奇"<654605042@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [arxeiss/fast-3d-object-detection] Cannot fine the dataset "CMP-8objs" (#1)




Please, check the code again. I found I did not upload everything. There is some cleaning done in the code.
